# Generated by Django 6.0.3 on 2026-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_comment_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL (e.g. from TheCocktailDB API).",
                max_length=500,
            ),
        ),
    ]
